cc_binary(
    features = ["use_linker"],
    name = "ResourceImporterFBX.dll",
    srcs = ["sample/addons/ResourceImporterFBX/src/ResourceImporterFBX.cpp",
    "sample/addons/ResourceImporterFBX/src/ResourceImporterFBX.h",
    "sample/addons/ResourceImporterFBX/src/ofbx.cpp",
    "sample/addons/ResourceImporterFBX/src/ofbx.h",
    "sample/addons/ResourceImporterFBX/src/miniz.c",
    "sample/addons/ResourceImporterFBX/src/miniz.h",
    "godot_headers/godot/gdnative.h",
    "godot_headers/godot/string.h",
    "godot_headers/godot/vector2.h",
    "godot_headers/godot/rect2.h",
    "godot_headers/godot/vector3.h",
    "godot_headers/godot/basis.h",
    "godot_headers/godot/quat.h",
    "godot_headers/godot/transform2d.h",
    "godot_headers/godot/variant.h",
    "godot_headers/godot/array.h",
    "godot_headers/godot/pool_arrays.h",
    "godot_headers/godot/color.h",
    "godot_headers/godot/dictionary.h",
    "godot_headers/godot/node_path.h",
    "godot_headers/godot/plane.h",
    "godot_headers/godot/rect3.h",
    "godot_headers/godot/rid.h",
    "godot_headers/godot/transform.h",
    "godot_headers/godot_nativescript.h",
    "cpp_bindings/include/core/Godot.hpp",
    "cpp_bindings/include/Reference.hpp",
    "cpp_bindings/include/core/CoreTypes.hpp",
    "cpp_bindings/include/core/Defs.hpp",
    "cpp_bindings/include/core/Array.hpp",
    "cpp_bindings/include/core/String.hpp",
    "cpp_bindings/include/core/Basis.hpp",
    "cpp_bindings/include/core/Vector3.hpp",
    "cpp_bindings/include/core/Color.hpp",
    "cpp_bindings/include/core/Dictionary.hpp",
    "cpp_bindings/include/core/Variant.hpp",
    "cpp_bindings/include/core/NodePath.hpp",
    "cpp_bindings/include/core/Plane.hpp",
    "cpp_bindings/include/core/PoolArrays.hpp",
    "cpp_bindings/include/core/Vector2.hpp",
    "cpp_bindings/include/core/Quat.hpp",
    "cpp_bindings/include/core/Rect2.hpp",
    "cpp_bindings/include/core/Rect3.hpp",
    "cpp_bindings/include/core/RID.hpp",
    "cpp_bindings/include/core/Transform.hpp",
    "cpp_bindings/include/core/Transform2D.hpp",
    "cpp_bindings/include/core/Ref.hpp",
    "cpp_bindings/include/Object.hpp",
    "cpp_bindings/include/core/GodotGlobal.hpp",
    "cpp_bindings/include/ArrayMesh.hpp",
    "cpp_bindings/include/Mesh.hpp",
    "cpp_bindings/include/Resource.hpp",
    "cpp_bindings/include/EditorImportPlugin.hpp",
    "cpp_bindings/include/ClassDB.hpp",
    "cpp_bindings/include/File.hpp",
    "cpp_bindings/include/ProjectSettings.hpp",
    "cpp_bindings/include/ResourceSaver.hpp",
    "cpp_bindings/include/SurfaceTool.hpp",
    ],    
    copts = ["-Igodot_headers/",
    "-Icpp_bindings/include/", 
    "-Icpp_bindings/include/core/",
    ],
    data = glob(["godot_cpp_bindings.dll", "godot_cpp_bindings.pdb", "cube.fbx", "godot_cpp_core.dll", "godot_cpp_core.pdb", "addons/**"]),
    linkstatic = 0,
    linkshared = 1,
    linkopts = ["-DEFAULTLIB:godot_fork/bin/godot.windows.tools.64.lib",
    "-DEFAULTLIB:cpp_bindings/bin/godot_cpp_bindings.lib"
    ]
)

load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar", "pkg_deb")

pkg_tar(
    name = "resource-importer-fbx-bin",
    strip_prefix = "sample",
    package_dir = "addons/ResourceImporterFBX/lib",
    files = ["//:ResourceImporterFBX.dll"],
    mode = "0755",
)

pkg_tar(
    name = "resource-importer-fbx-data",
    strip_prefix = "sample",
    package_dir = "",
    files = glob(["sample/**"], exclude=["*.import", "import"]),
    mode = "0755",
)

pkg_tar(
    name = "resource-importer-fbx",
    extension = "tar.gz",
    deps = [
        ":resource-importer-fbx-bin",
        ":resource-importer-fbx-data",
    ],
)