cc_binary(
    features = ["use_linker"],
    name = "SimpleClass.dll",
    srcs = ["sample/addons/SimpleClass/src/SimpleClass.cpp",
    "CppBindings/include/gdnative.hpp",
    "CppBindings/include/core/vector2.hpp",
    "CppBindings/include/core/rect2.hpp",
    "CppBindings/include/core/vector3.hpp",
    "CppBindings/include/core/basis.hpp",
    "CppBindings/include/core/quat.hpp",
    "CppBindings/include/core/transform2d.hpp",
    "CppBindings/include/core/variant.hpp",
    "CppBindings/include/core/array.hpp",
    "CppBindings/include/core/color.hpp",
    "CppBindings/include/core/dictionary.hpp",
    "CppBindings/include/Node.hpp",
    "CppBindings/include/core/plane.hpp",
    "CppBindings/include/core/AABB.hpp",
    "CppBindings/include/core/rid.hpp",
    "CppBindings/include/core/transform.hpp",
    "CppBindings/include/core/GodotGlobal.hpp",    
    "CppBindings/include/core/string.hpp",
    "CppBindings/include/Reference.hpp",
    "CppBindings/include/core/Defs.hpp",
    "CppBindings/include/core/Array.hpp",
    "CppBindings/include/core/String.hpp",
    "CppBindings/include/core/Basis.hpp",
    "CppBindings/include/core/Vector3.hpp",
    "CppBindings/include/core/Color.hpp",
    "CppBindings/include/core/Dictionary.hpp",
    "CppBindings/include/core/Variant.hpp",
    "CppBindings/include/core/NodePath.hpp",
    "CppBindings/include/core/Plane.hpp",
    "CppBindings/include/core/PoolArrays.hpp",
    "CppBindings/include/core/Vector2.hpp",
    "CppBindings/include/core/Quat.hpp",
    "CppBindings/include/core/Rect2.hpp",
    "CppBindings/include/core/RID.hpp",
    "CppBindings/include/core/Transform.hpp",
    "CppBindings/include/core/Transform2D.hpp",
    "CppBindings/include/core/Ref.hpp",
    "CppBindings/include/Object.hpp",
    "CppBindings/include/ArrayMesh.hpp",
    "CppBindings/include/Mesh.hpp",
    "CppBindings/include/Resource.hpp",
    "CppBindings/include/EditorImportPlugin.hpp",
    "CppBindings/include/ClassDB.hpp",
    "CppBindings/include/File.hpp",
    "CppBindings/include/ProjectSettings.hpp",
    "CppBindings/include/ResourceSaver.hpp",
    "CppBindings/include/SurfaceTool.hpp",
    "GodotHeaders/gdnative_api_struct.gen.h",
    "CppBindings/bin/godot_cpp_bindings.lib",
    ], 
    includes = ["Godot/modules/gdnative/include",
    "CppBindings/include/",
    "CppBindings/include/core",],  
    copts = ["-O2", "/MT"],
    data = glob(["godot_cpp_bindings.dll", "godot_cpp_bindings.pdb", "cube.fbx", "godot_cpp_core.dll", "godot_cpp_core.pdb", "addons/**"]),
    linkstatic = 1,
    linkshared = 1,
    linkopts = []
)

load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar", "pkg_deb")

pkg_tar(
    name = "itchio-bin",
    strip_prefix = "../Game/Sample",
    package_dir = "addons/SimpleClass/lib",
    srcs = ["//:SimpleClass.dll"],
    mode = "0755",
)

pkg_tar(
    name = "itchio-data",
    strip_prefix = "../Game/Sample",
    package_dir = "",
    srcs = glob(["sample/**"], exclude=["*.import", "import"]),
    mode = "0755",
)

pkg_tar(
    name = "itchio",
    extension = "tar.gz",
    deps = [
        ":itchio-bin",
        ":itchio-data",
    ],
)