#!python
import os

env = Environment()

platform = ARGUMENTS.get("platform", "p")

def add_sources(sources, dir):
    for f in os.listdir(dir):
        if f.endswith(".cpp"):
            sources.append(dir + "/" + f)

if platform == "linux":
    if ARGUMENTS.get("use_llvm", "no") == "yes":
        env["CXX"] = "clang++"
    env.Append(CCFLAGS = ['-g','-O3', '-std=c++14', '-Wno-writable-strings'])
    env.Append(LINKFLAGS = ['-Wl,-R,\'$$ORIGIN\''])
    env.Append(CPPPATH=['/usr/include/godot/', '/usr/include/godot/godot_cpp/', '/usr/include/godot/godot_cpp/core'])
    env.Append(LIBS=['godot_cpp_core', 'godot_cpp_bindings'])
    env.Append(LIBPATH=["../lib"])

if platform == "windows":
    env.Append(CPPPATH=[ '../godot_headers/', '../../FBX SDK/2018.1.1/include/', '../cpp_bindings/include/', '../cpp_bindings/include/core/'])
    env.Append(LIBS=['godot_fork/bin/godot.windows.tools.64', 'cpp_bindings/bin/godot_cpp_core', 'cpp_bindings/bin/godot_cpp_bindings', '../FBX SDK/2018.1.1/lib/vs2015/x64/release/libfbxsdk']) 

sources = ["ResourceImporterFBX.cpp"]

library = env.SharedLibrary(target='../sample/addons/ResourceImporterFBX/lib/ResourceImporterFBX', source=sources)
Default(library)

